# Generated by Django 4.2.4 on 2024-04-01 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodity_app', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='分类名',
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('创建日期', models.DateTimeField(auto_now_add=True)),
                ('用户', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车模型',
                'verbose_name_plural': '购物车模型',
                'db_table': 'shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('详情描述', models.TextField()),
                ('详情图片', models.ImageField(upload_to='product_images/')),
                ('创建日期', models.DateTimeField(auto_now_add=True)),
                ('产品详情', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='commodity_app.product')),
            ],
            options={
                'verbose_name': '产品详情模型',
                'verbose_name_plural': '产品详情模型',
                'db_table': 'productdetail',
            },
        ),
    ]
