# Generated by Django 4.2.4 on 2024-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0003_rename_category_name_category_分类名_shoppingcart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='产品图片',
            field=models.ImageField(default='placeholder_image.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
