# Generated by Django 4.2.4 on 2024-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0004_product_产品图片'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='产品图片',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
