# Generated by Django 4.2.4 on 2024-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0005_alter_product_产品图片'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='产品图片',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='详情图片',
            field=models.ImageField(upload_to='shopping/shop/commodity_app/static/images/'),
        ),
    ]
