# Generated by Django 4.2.4 on 2024-04-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0006_alter_product_产品图片_alter_productdetail_详情图片'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='产品图片',
        ),
    ]
