# Generated by Django 4.2.4 on 2024-04-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='用户',
        ),
    ]
