# Generated by Django 4.2.4 on 2024-04-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0010_rename_用户_order_user_rename_用户_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='产品名称',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commodity_app.product'),
        ),
    ]
