# Generated by Django 4.2.4 on 2024-04-03 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodity_app', '0011_shoppingcart_产品名称'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('商品数量', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_items', to=settings.AUTH_USER_MODEL)),
                ('产品名称', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.product')),
            ],
            options={
                'verbose_name': '购物车条目',
                'verbose_name_plural': '购物车条目',
                'db_table': 'shopping_cart_item',
            },
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='产品名称',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
