# Generated by Django 4.2.4 on 2024-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0012_shoppingcartitem_remove_shoppingcart_产品名称_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('产品名称', models.CharField(max_length=100)),
                ('销售数量', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '销售数据',
                'verbose_name_plural': '销售数据',
                'db_table': 'order',
            },
        ),
    ]
