# Generated by Django 4.2.4 on 2024-04-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_success',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('商品名称', models.CharField(max_length=100)),
                ('销售数量', models.PositiveIntegerField()),
                ('销售日期', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'db_table': 'order_success',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
